---
title: "PR 1"
subtitle: "Communication Skills for ICT Professionals"
author: Alejandro Pérez Bueno
date: today
date-format: "MMM DD, YYYY"
toc: true
toc-title: "Table of Contents"
linkcolor: blue
documentclass: report
link-citations: true
link-bibliography: true
format:
  gfm: default
  pdf:
    linestretch: 1.25
    code-overflow: wrap
    keep-tex: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    include-in-header:
      text: |
        \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhead[C]{UOC}
          \fancyhead[R]{aperez-b@uoc.edu}
          \fancyfoot{}
          \fancyfoot[C]{\thepage}
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

{{< pagebreak >}}

## Email to Julia from Medicat

> Dear Julia,
>
> Thank you for reaching out to us. My name is Alex and I am head of *InfoFarma*'s' technical department. Indeed, we *have* heard of *Medicat*. We are truly inspired by your work in developing countries, reaching millions of families in need. Your work reminds us that not everyone has the same access to pharmaceuticals, and that we must take action in whatever way possible to improve their dire situation.
>
> Moved by this call to action, our IT team at *InfoFarm* would like to embark on this project with you to digitize the NGO. Now that *Medicat* operates in several countries it is crucial that every country manages its own inventory to ensure that they operate independently of other countries.
>
> Such an inventory should be able to alert when certain pharmaceuticals are low in stock, so as to automatically request more depending on the varying demands of each country. Furthermore, the website should be able calculate and predict the demands of each country in order to ensure that no pharmaceutical is wasted.
>
> These are but a few ideas we believe could kick-off this project. While fixing a budget or time frame for this project requires careful planning and coordination, our experience with other clients tells us that the cost of a project of this size can take 1-2 years to reach production with a budget of roughly €300K, including the maintenance and support of the solution.
>
> If it is okay with you, we could arrange an in-person meeting next-week to discuss the details of this project. Once again, we at *InfoFarma* are thrilled to spearhead this overhaul and are eager to be a part of your journey.
>
> We look forward to hearing back from you. Regards,
>
> Alex
